### ISSUE TITLE
No More Stats after reverse proxy

### ISSUE THREAD

**Issue by GSB-Deleven** [SelfhostedPro/Yacht#231]
Hi, First of all, i love Yacht, seems way more intuitive then portainer. (And looks a lot better)

Now to the issue.
So if I access yacht with my internal IP, everything is fine
![image](https://user-images.githubusercontent.com/35196079/103787265-a7994900-503d-11eb-855b-73c6c3c3bca5.jpeg)

But if I access it with the reverse proxy, the stats don't show anymore. 
![image](https://user-images.githubusercontent.com/35196079/103787444-dfa08c00-503d-11eb-835f-9add769ec244.jpeg)

Everything else works just fine.
As this overview is one of the things I love the most about yacht (coming from Synology which looks similar) i thought a let you know and i would love if you could make it work 👍 

Setup:
Ubuntu 20.10
Docker version 20.10.2, build 2291f61
docker-compose version 1.27.4, build unknown

```yaml
version: '3.2'
  
services:
  yacht:
    ports:
        - '8001:8000'
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/home/deleven/docker/configs/yacht:/config'
    image: selfhostedpro/yacht
    restart: unless-stopped
```

Thank you very much in advance
