### ISSUE TITLE
Blank page when loading certain projects

### ISSUE THREAD

**Issue by alexandzors** [SelfhostedPro/Yacht#298]
App version: **v0.0.6-alpha-2021-02-19--20**

How to reproduce:
1. Deploy Yachet via docker-compose using example in docs.
2. Login and create a new project using the provided docker-compose file below.
```
version: "3.6"
services:
 jackett:
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "1"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: linuxserver/jackett
    ports:
      - "9117:9117"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - "/opt/docker/Jackett:/config"
      - "/media/downloads/jackett:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
```
3. Label the project "Jackett" and submit.
4. Reload the projects directory and click on the Jackett project.
![image](https://user-images.githubusercontent.com/25626115/108618505-e8ca9a00-73ec-11eb-8eac-8018878b0150.png)

Seems to be only affecting certain projects. As I have others that load just fine. Deleting and recreating experiences the same issue.
