### ISSUE TITLE
No Stats When I use Yacht on Debian Testing

### ISSUE THREAD

**Issue by My-Zones** [SelfhostedPro/Yacht#320]
**Describe the bug**
The stats don't show anything when I use Yatch on Debian Testing  

**Screenshots**
Stats on Debian Stable 
<img width="822" alt="Capture d’écran 2021-02-26 à 16 00 19" src="https://user-images.githubusercontent.com/40335475/109316724-33647000-784c-11eb-9805-b2ad4432cecf.png">

Stats on Debian Testing
<img width="859" alt="Capture d’écran 2021-02-26 à 15 57 46" src="https://user-images.githubusercontent.com/40335475/109316801-45461300-784c-11eb-9060-d8e7e5d0f01e.png">

**Desktop :**
 - OS: Debian Testing
 - Docker version 20.10.3, build 48d30b5
 - docker-compose version 1.28.4, build cabd5cfb
 - Browser: Firefox, Chrome, Safari
 - Yacht Version : Latest

```
version: '3'
services:
  yacht:
    image: selfhostedpro/yacht:latest
    container_name: Yacht
    network_mode: bridge
    volumes:
      - /srv/Yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:8000
    restart: unless-stopped
```

Thank you very much in advance

**Comment by SelfhostedPro** [comment]
Can you try using the devel tag and see if it works for you? I made some changes yesterday that I'm testing related to this there.

```yml
version: '3'
services:
  yacht:
    image: selfhostedpro/yacht:devel
    container_name: Yacht
    network_mode: bridge
    volumes:
      - /srv/Yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:8000
    restart: unless-stopped
```
