### ISSUE TITLE
[FYI] Documentation about Socket-Proxy usage

### ISSUE THREAD

**Issue by Bockiii** [SelfhostedPro/Yacht#390]
Hi,

since I had to look for the solution, maybe you can add this to your documentation.

If you use (or want to use) a socket-security-container in between your yacht/portainer/traefik containers (like tecnativa/docker-socket-proxy ) there are two things you need to add: The network of the socket-proxy and the "DOCKER_HOST" env on the Yacht service. 

Example:

```
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: always
    networks:
      socket_proxy:
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped
    networks:
      - socket_proxy
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
```

I omitted all the socket-proxy env variables, but you get the gist. Basically: Put them both in the same network, then set the "DOCKER_HOST" env in the Yacht container to the name of the socket proxy.

Greetings
