### ISSUE TITLE
Blank page/network.join error when attempting to view Project w/MacVlan

### ISSUE THREAD

**Issue by Ixian** [SelfhostedPro/Yacht#399]
Using a 3.9 compose template, the project details page shows up blank and throws the attached error in console if compose references external MacVlans.
![Screenshot 2021-05-27 170517](https://user-images.githubusercontent.com/1704047/119903356-3b48b480-bf0e-11eb-9576-3e700ffe900c.png)

Compose file:
```
version: "3.9"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=8675309
      - PGID=8675309
      - TZ=America/Chicago
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=
      - MYSQL_HOST=nextcloud
      - NEXTCLOUD_DATA_DIR=/data
    volumes:
      - nextcloud:/config
      -/nextcloud:/data
    ports:
      - 443:443
      - 80:80
    networks:
        media_vlan:
            ipv4_address: 192.168.86.235
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud_db
    environment:
      - PUID=8675309
      - PGID=8675309
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - nextcloud_db:/config
    networks:
        media_vlan:
            ipv4_address: 192.168.86.236
    restart: unless-stopped
  cloud:
    image: collabora/code
    container_name: collabora
    environment:
      - domain=
    cap_add:
     - MKNOD
    ports:
      - 9980:9980
    networks:
        media_vlan:
            ipv4_address: 192.168.86.237
    restart: unless-stopped   
networks:
    media_vlan:
        external: true
volumes:
  nextcloud:
    name: "dozer/docker-volumes/nextcloud"
    driver: "zfs"
    driver_opts:
      atime: "off"
  nextcloud_db:
    name: "dozer/docker-volumes/nextcloud_db"
    driver: "zfs"
    driver_opts:
      atime: "off"
```

Any ideas? Tried it with the GA release as well as v0.0.7-alpha-2021-05-07--12. Thanks!
