### ISSUE TITLE
[Bug Report] Incorrect CPU usage shown

### ISSUE THREAD

**Issue by agneevX** [SelfhostedPro/Yacht#420]
**Describe the bug**

Yacht shows incorrect CPU usage:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/19761269/126028590-2aede408-51ca-49a8-be6f-ddeb8c2d96b0.png">

Portainer:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/19761269/126028594-cce438fc-62a5-4e2f-89a7-75808989c39c.png">

```yml
# compose.yml
version: "3.8"
services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht:devel
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - SECRET_KEY=key
      - DISABLE_AUTH=True
    volumes:
      - /opt/appdata/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
```

**Expected behavior**

Yacht would show the correct CPU usage

**Environment**
 - OS: Ubuntu 20.04 arm64
 - Browser: Safari, MobileSafari
 - Yacht Version: devel-2021-06-25--13

**Additional context**

** Logs **
