### ISSUE TITLE
[Bug Report] 'Image not known' when trying to initialize template (Podman)

### ISSUE THREAD

**Issue by arvigeus** [SelfhostedPro/Yacht#547]
I get 404 when it tries to POST to `http://localhost:8000/api/apps/deploy`. Response is `{"detail":"no such image: lscr.io/linuxserver/bazarr:latest: image not known"}` (this happens with any template)

I am using Podman. This is my yach compose:

```yaml
---
version: "3"
services:
  yacht:
    container_name: yacht
    hostname: yacht
    privileged: true
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
    volumes:
      - ./data/config:/config:Z
      - ${DOCKER_SOCK}:/var/run/docker.sock:Z
    image: ghcr.io/selfhostedpro/yacht:latest
    networks:
      - DOCKER_NETWORK

networks:
  DOCKER_NETWORK:
    external: true
    name: shared
```

(note: I am able to create stacks with Portainer)
